version: "3.8"
services:
  sdt-db:
    container_name: sdt-db
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: sdt-test
      PGDATA: /var/lib/postgresql/data
    networks:
      sdtnet:
    volumes:
      - postgres:/var/lib/postgresql/data
networks:
  sdtnet:
    driver: bridge
    ipam:
      driver: default
volumes:
  postgres:
